CREATE DATABASE BAITHI4

USE BAITHI4

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY,
	TENKH VARCHAR(50), 
	DIACHI VARCHAR(50), 
	LOAIKH VARCHAR(50)
)

CREATE TABLE LOAICAY
(
	MALC CHAR(4) PRIMARY KEY, 
	TENLC VARCHAR(50), 
	XUATXU VARCHAR(50), 
	GIA MONEY
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) PRIMARY KEY, 
	NGHD SMALLDATETIME, 
	MAKH CHAR(4), 
	KHUYENMAI INT
)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH)
REFERENCES KHACHHANG (MAKH)

CREATE TABLE CTHD
(
	SOHD CHAR(5) NOT NULL, 
	MALC CHAR(4) NOT NULL, 
	SOLUONG INT
)

ALTER TABLE CTHD
ADD CONSTRAINT PK_CTHD_HD_LC PRIMARY KEY (SOHD, MALC)


INSERT INTO KHACHHANG (MAKH, TENKH,DIACHI, LOAIKH) VALUES ('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai')
INSERT INTO KHACHHANG (MAKH, TENKH,DIACHI, LOAIKH) VALUES ('KH02', 'Ivone Dieu Linh', 'Da Nang', 'Thuong xuyen')
INSERT INTO KHACHHANG (MAKH, TENKH,DIACHI, LOAIKH) VALUES ('KH03', 'Emma Nhat Khanh', 'TP.HCM', 'Vang lai' )
SELECT * FROM KHACHHANG
  

INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA ) VALUES('LC01', 'Xuong rong tai tho', 'Mexico', 180000)
INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA ) VALUES('LC02', 'Sen thach ngoc', 'Anh', 300000)
INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA ) VALUES('LC03', 'Ba mau rau', 'Nam Phi', 270000 )
SELECT * FROM LOAICAY
  

SET DATEFORMAT DMY
INSERT INTO HOADON (SOHD, NGHD, MAKH, KHUYENMAI ) VALUES ('00001', '22/11/2017', 'KH01', 5)
INSERT INTO HOADON (SOHD, NGHD, MAKH, KHUYENMAI ) VALUES ('00002', '04/12/2017', 'KH03', 5)
INSERT INTO HOADON (SOHD, NGHD, MAKH, KHUYENMAI ) VALUES ('00003', '10/12/2017', 'KH02', 10)
SELECT * FROM HOADON
   

INSERT INTO CTHD (SOHD, MALC, SOLUONG ) VALUES ('00001', 'LC01', 1)
INSERT INTO CTHD (SOHD, MALC, SOLUONG ) VALUES ('00001', 'LC02', 2)
INSERT INTO CTHD (SOHD, MALC, SOLUONG ) VALUES ('00003', 'LC03', 5 )
SELECT * FROM CTHD


CREATE TRIGGER I_U_LC
ON LOAICAY
FOR INSERT, UPDATE
AS
BEGIN
	IF (EXISTS (	SELECT *
					FROM INSERTED I 
					WHERE XUATXU = 'Anh' AND GIA <=250000
				)
		)
		BEGIN 
		PRINT 'TAT CA CAC MAT HANG XUATU TU ANH PHAI CO GIA > 250.000'
		ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN
		PRINT 'THEM HAOC SUA THANH CONG'
		END
END;

INSERT INTO LOAICAY(MALC, TENLC, XUATXU, GIA ) VALUES('LC04', 'Ba mau rau', 'Anh', 270000 )
SELECT * FROM LOAICAY
DELETE FROM LOAICAY WHERE MALC = 'LC04'


CREATE TRIGGER I_U_HD
ON HOADON
FOR INSERT , UPDATE
AS
BEGIN
	IF (EXISTS (SELECT *
				FROM INSERTED I JOIN CTHD ON CTHD.SOHD = I.SOHD
				WHERE KHUYENMAI <> 10 
				GROUP BY I.SOHD
				HAVING SUM(SOLUONG) >= 5
				)
		)
		BEGIN 
		PRINT 'HOADON MAU VOI TONGSOLUONG >= 5 THI DUOC GIAMGIA 10% '
		ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN 
		PRINT 'THEM HOAC SUA THANH CONG'
		END
END;

INSERT INTO HOADON (SOHD, NGHD, MAKH, KHUYENMAI ) VALUES ('00003', '10/12/2017', 'KH02', 10)
SELECT * FROM HOADON
UPDATE HOADON
SET KHUYENMAI = 10
WHERE SOHD = '00003'


CREATE TRIGGER I_U_CTHD
ON CTHD
FOR INSERT , UPDATE
AS
BEGIN
	IF (EXISTS (SELECT *
				FROM INSERTED I JOIN HOADON HD ON HD.SOHD = I.SOHD
				WHERE KHUYENMAI <> 10 
				GROUP BY I.SOHD
				HAVING SUM(SOLUONG) >= 5
				)
		)
		BEGIN 
		PRINT 'HOADON MAU VOI TONGSOLUONG >= 5 THI DUOC GIAMGIA 10% '
		ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN 
		PRINT 'THAMHOAC SUA THANH CONG'
		END
END;

INSERT INTO CTHD (SOHD, MALC, SOLUONG ) VALUES ('00003', 'LC03', 5 )
SELECT * FROM CTHD
INSERT INTO CTHD (SOHD, MALC, SOLUONG ) VALUES ('00003', 'LC03', 5 )
UPDATE CTHD
SET SOLUONG = 5
WHERE SOHD = '00001' AND MALC = 'LC02'


SELECT *
FROM HOADON
WHERE MONTH(NGHD) IN (10,11,12) AND YEAR(NGHD) = 2017
ORDER BY KHUYENMAI ASC


SELECT LC.MALC, TENLC, XUATXU, GIA
FROM LOAICAY LC JOIN CTHD ON LC.MALC = CTHD.MALC 
		JOIN HOADON HD ON HD.SOHD = CTHD.SOHD 
WHERE MONTH(NGHD) = 12 AND SOLUONG = ( SELECT MIN(SOLUONG)
										FROM CTHD C JOIN HOADON H ON C.SOHD = H.SOHD
										WHERE MONTH(NGHD) = 12
										)


SELECT LC.MALC, TENLC, XUATXU, GIA
FROM LOAICAY LC JOIN CTHD ON CTHD.MALC = LC.MALC
		JOIN HOADON HD ON HD.SOHD = CTHD.SOHD
		JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE LOAIKH = 'Thuong xuyen' AND LC.MALC IN  ( SELECT L.MALC
												FROM LOAICAY L JOIN CTHD C ON C.MALC = L.MALC
														JOIN HOADON H ON H.SOHD = C.SOHD
														JOIN KHACHHANG K ON K.MAKH = H.MAKH
												WHERE LOAIKH = 'Vang lai' 
												)


SELECT KH.MAKH, TENKH, DIACHI, LOAIKH
FROM KHACHHANG KH JOIN HOADON HD ON HD.MAKH = KH.MAKH
WHERE NOT EXISTS(	SELECT *
					FROM LOAICAY LC
					WHERE NOT EXISTS (	SELECT *
										FROM CTHD
										WHERE LC.MALC = CTHD.MALC AND HD.SOHD = CTHD.SOHD
									)
				)



